
name: Pipeline CI/CD projet m1meldinodeapp
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: meldiapp

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps: 
    
      - name: checkout
        uses: actions/checkout@v4

      - name: lancer les tests
        run: ls -lah

      